routes/web.php
<?php

use Carbon\Carbon;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/dash', function () {
    return view('dashboard.dashboard');
});

Route::get('/calendar',function (){
    return view('calendar');
});
Route::get('/time', function (){
    // get the current time
    $current = new Carbon('First Day of November 2020');

// add 30 days to the current time
    echo $current->toFormattedDateString();

//    $new = new Carbon('First day of November 2020');
    echo "<br>";
    echo $past =$current->subMonth()->diffForHumans();
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/projects','AdminController@showprojects')->name('admin.projects');
    Route::get('/bugs','AdminController@showbugs')->name('admin.bugs');
    Route::get('/users','AdminController@showusers')->name('admin.users');
    Route::delete('/projects/destroy/{id}','AdminController@destroyProject')->name('admin.projects.destroy');
    Route::get('/pj_details/{id}','AdminController@show_project_details');
    Route::get('/bg_details/{id}','AdminController@show_bug_details');
    Route::get('/user_details/{id}','AdminController@show_user_details');
    Route::get('/user_edit/{id}', 'AdminController@edit_user');
    Route::put('/bug_edit/{id}','AdminController@edit_bug')->name('admin.bugs.update');
    Route::delete('/users/destroy/{id}', 'AdminController@userDelete')->name('admin.users.destroy');
    Route::delete('/bugs/destroy/{id}','AdminController@bugDelete')->name('admin.bugs.destroy');
    Route::post('/user_reg','AdminController@register_user')->name('admin.users.create');
    Route::put('/projects/{id}','AdminController@editProject')->name('admin.projects.update');
});

Route::middleware(['auth'])->group(function () {
    Route::post('projects/adduser','ProjectsController@addtester')->name('projects.addtester');
    Route::get('bugs/create/{project_id?}', 'BugsController@create');
    Route::resource('projects', 'ProjectsController');
    Route::resource('bugs', 'BugsController');
    Route::resource('users', 'UsersController');
    Route::resource('events', 'EventController');
    Route::resource('comments','CommentsController');
    Route::get('bug_reports','ReportsController@bugs');
    Route::get('project_reports','ReportsController@projects');
    Route::post('bug_pdf_export','ReportsController@bug_export');
    Route::get('/bug_details/{id}','ReportsController@pdf_bug');
    Route::get('projects_pdf_export','ReportsController@project_export');
    Route::post('fileUpload',['as' => 'image.add','uses' => 'UsersController@avatarUpload']);
    Route::post('attachmentUpload',['as' =>'bug_attachment.add', 'uses'=>'BugsController@attachmentUpload']);
    Route::post('/projects/search', ['as' => 'search_projects', 'uses' => 'ProjectsController@search_projects']);
    Route::post('bugs/search', ['as' => 'search_bugs', 'uses' => 'BugsController@search_bugs']);
    Route::get('/help','HelpController@index');
    Route::get('/faq/{faq}', 'HelpController@show')->name('help.faq');

    Route::get('/markAsRead', function (){
        auth()->user()->unreadNotifications->markAsRead();
    });
});

resources/views/partials/comments.blade.php
<div class="row">
    <div class="col-12">
        <div class="card" style="margin-left: 3rem;">
            <div class="card-header">
                <h3 class="card-title">Recent Activity</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i></button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i></button>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">

                        <div class="row">
                            <div class="col-12">
                                @foreach($comments as $comment)
                                    <div class="comment-container">
                                        <div class="post">
                                            <div class="user-block">
                                                <img class="img-circle img-bordered-sm" src="../../uploads/avatars/{{$comment->user->avatar}}" alt="user image">
                                                <span class="username">
                                                            <a href="#">{{$comment->user->name.' '.$comment->user->lastname}} </a>
                                                         </span>
                                                <span class="description">Shared publicly - {{$comment->created_at}}</span>
                                            </div>
                                            <!-- /.user-block -->
                                            <p>
                                                {{$comment->body}}
                                            </p>
                                            <p> <b> Url:</b>{{$comment->url}}</p>
                                            @if(is_countable($comment->attachments) && count($comment->attachments) < 1)

                                            @else
                                                <p><b>Attachments :</b>

                                                    <a href="../../uploads/attachments/{{$comment->attachments}}" target="_blank" class="link-black text-sm"><i class="fas fa-link mr-1"></i>{{$comment->attachments}}</a>
                                                    <img class="img-fluid" src="../../uploads/attachments/{{$comment->attachments}}" alt="..." l style="height:150px;width:250px" >

                                                    {{--<ul>--}}
                                                    {{--@foreach($comment->attachments as $attachment)--}}
                                                    {{--<li>{{$attachment}}</li>--}}
                                                    {{--@endforeach--}}

                                                    {{--</ul>--}}
                                                </p>
                                            @endif
                                            @if(Auth::user()->id == $comment->user_id )

                                                <a href="" class="link-black text-sm" onclick="$(this).next('div').slideToggle(1000);return false"><i class="fas fa-edit"></i>Edit Comment</a>
                                                {{--Update Comment Div--}}
                                                <div style="display: none">
                                                    <form action="{{route('comments.update',$comment->id)}}" method="POST">
                                                        {{csrf_field()}}
                                                        <input type="hidden" name="_method" value="put">
                                                        <input type="hidden" name="comment_id "value="{{$comment->id}}">
                                                        <div class="form-group">
                                                            <label for="comment-content">Comment</label>
                                                            <textarea required placeholder="Enter comment"
                                                                      style="resize: vertical "
                                                                      id="comment-body"
                                                                      name="body"
                                                                      rows="2" spellcheck="false"
                                                                      class="form-control autosize-target text-left" >{{$comment->body}}
                                                                </textarea>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="comment-content"> Attachment Url</label>
                                                            <input type="text"
                                                                   style="resize:vertical"
                                                                   id="comment-attach"
                                                                   name="url"
                                                                   value="{{$comment->url}}"
                                                                   class="form-control autosize-target text-left">
                                                            &nbsp;
                                                        </div>

                                                        <div class="modal-footer justify-content-between">
                                                            <button type="submit" class="btn btn-primary btn-sm">Save Changes</button>
                                                        </div>
                                                    </form>

                                                </div>



                                                <a style="cursor: pointer;"  class="delete-comment link-black text-sm" token="{{ csrf_token() }}" comment-did="{{ $comment->id }}"><i class="fas fa-trash"></i>Delete Comment</a>

                                            @endif


                                        </div>
                                        <hr>
                                    </div>

                                @endforeach
                            </div>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>

</div>

resources/views/partials/errors.blade.php
@if (session()->has('errors'))
    <div class="col-md-9">
        <div class="alert alert-dismissable alert-danger" style="margin-top: 5rem;margin-left: 16rem">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {<strong>
            {!! session()->get('errors') !!}
        </strong>
    </div>
    </div>
@endif

resources/views/partials/success.blade.php
@if (session()->has('success'))
    <div class="col-md-9">
    <div class="alert alert-dismissable alert-success fade show" style="margin-top: 5rem;margin-left: 16rem">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>
            {!! session()->get('success') !!}
        </strong>
    </div>
    </div>
    @endif