routes/web.php
<?php

use Carbon\Carbon;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/dash', function () {
    return view('dashboard.dashboard');
});

Route::get('/calendar',function (){
    return view('calendar');
});
Route::get('/time', function (){
    // get the current time
    $current = new Carbon('First Day of November 2020');

// add 30 days to the current time
    echo $current->toFormattedDateString();

//    $new = new Carbon('First day of November 2020');
    echo "<br>";
    echo $past =$current->subMonth()->diffForHumans();
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/projects','AdminController@showprojects')->name('admin.projects');
    Route::get('/bugs','AdminController@showbugs')->name('admin.bugs');
    Route::get('/users','AdminController@showusers')->name('admin.users');
    Route::delete('/projects/destroy/{id}','AdminController@destroyProject')->name('admin.projects.destroy');
    Route::get('/pj_details/{id}','AdminController@show_project_details');
    Route::get('/bg_details/{id}','AdminController@show_bug_details');
    Route::get('/user_details/{id}','AdminController@show_user_details');
    Route::get('/user_edit/{id}', 'AdminController@edit_user');
    Route::put('/bug_edit/{id}','AdminController@edit_bug')->name('admin.bugs.update');
    Route::delete('/users/destroy/{id}', 'AdminController@userDelete')->name('admin.users.destroy');
    Route::delete('/bugs/destroy/{id}','AdminController@bugDelete')->name('admin.bugs.destroy');
    Route::post('/user_reg','AdminController@register_user')->name('admin.users.create');
    Route::put('/projects/{id}','AdminController@editProject')->name('admin.projects.update');
});

Route::middleware(['auth'])->group(function () {
    Route::post('projects/adduser','ProjectsController@addtester')->name('projects.addtester');
    Route::get('bugs/create/{project_id?}', 'BugsController@create');
    Route::resource('projects', 'ProjectsController');
    Route::resource('bugs', 'BugsController');
    Route::resource('users', 'UsersController');
    Route::resource('events', 'EventController');
    Route::resource('comments','CommentsController');
    Route::get('bug_reports','ReportsController@bugs');
    Route::get('project_reports','ReportsController@projects');
    Route::post('bug_pdf_export','ReportsController@bug_export');
    Route::get('/bug_details/{id}','ReportsController@pdf_bug');
    Route::get('projects_pdf_export','ReportsController@project_export');
    Route::post('fileUpload',['as' => 'image.add','uses' => 'UsersController@avatarUpload']);
    Route::post('attachmentUpload',['as' =>'bug_attachment.add', 'uses'=>'BugsController@attachmentUpload']);
    Route::post('/projects/search', ['as' => 'search_projects', 'uses' => 'ProjectsController@search_projects']);
    Route::post('bugs/search', ['as' => 'search_bugs', 'uses' => 'BugsController@search_bugs']);
    Route::get('/help','HelpController@index');
    Route::get('/faq/{faq}', 'HelpController@show')->name('help.faq');

    Route::get('/markAsRead', function (){
        auth()->user()->unreadNotifications->markAsRead();
    });
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $fillable=[
        'pj_name',
        'pj_type',
        'owner',
        'status',
        'pj_description',
        'user_id',
    ];

    public function users(){
        return $this->belongsToMany('App\User');
    }
    public function bugs(){
        return $this->hasMany('App\Bug');
    }
    public function comments(){
        return $this->morphMany('App\Comment','commentable');
    }

}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Bug;
use App\Notifications\AddedToProject;
use App\Project;
use App\ProjectUser;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;


class ProjectsController extends Controller
{
    /**w
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $pjID =DB::table('projects')->pluck('id');
        if (Auth::user()->user_group=='Manager') {
            //to pick projects by a certain user
//            $projects = Project::where('owner', Auth::user()->name.' '.Auth::user()->lastname)->get();
            $projects = Project::where('user_id', Auth::user()->id)->get();

//            $bugcount = Bug::where('project_id',$pjID)->count();
            //to view all projects
            //$projects = Project::all();
            return view('projects.index', ['projects' => $projects]);

        }elseif(Auth::user()->user_group=='Test Engineer'){
//            $bugcount = Bug::where('project_id',$pjID)->count();

            $projects = DB::table('project_user')
                ->join('projects','projects.id','project_user.project_id')
                ->where('project_user.user_id',Auth::user()->id )
                ->get();

            return view('projects.index', ['projects' => $projects]);

        }elseif (Auth::user()->user_group == 'Developer'){
//            $bugcount = Bug::where('project_id',$pjID)->count();

            $projects = DB::table('bugs')
                ->join('projects','projects.id','bugs.project_id')
                ->where('bugs.assigned',Auth::user()->id)
                ->get();
            $projects = $projects->unique('pj_name');
            $projects = array_slice($projects->values()->all(), 0, 5, true);

            return view('projects.index',['projects'=>$projects]);
        }

    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Table::select('name','surname')->where('id', 1)->get();
        $users = DB::table('users')->where('user_group', 'Manager')->get();
        /*Model::where('id', 1)
             ->pluck('name', 'surname')
             ->all();*/
        /*$users = User::where('user_group','Manager')
             ->pluck('name','lastname')
              ->all();*/


        //return($users->name);
        return view('projects.create',['users' => $users]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$users = DB::table('users')->where('user_group', 'Manager')->get();

        $testers = DB::table('users')->where('user_group','Test Engineer')->get();
        if(Auth::check()) {
            $project = Project::create([
                'pj_name'=>$request->input('pj_name'),
                'pj_type'=>$request->input('pj_type'),
                'pj_description' =>$request->input('pj_description'),
                'owner' => $request->input('owner'),
                'user_id'=>Auth::user()->id
            ]);
            //if project was created successfully
            if ($project) {
                return redirect()->route('projects.show', ['project' => $project->id,'testers'=> $testers ])
                    ->with('success', 'Project created successfully');
            }
        }
        //if not created successfully
        return back()->withInput()->with('errors','Error creating new project');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
        $testers = DB::table('users')->where('user_group','Test Engineer')->get();
        $project = Project::where('id',$project->id)->first();

        return view('projects.show',['project'=>$project ,'testers'=> $testers]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
        $project = Project::find($project->id);
        $users = DB::table('users')->where('user_group', 'Manager')->get();

        return view('projects.edit',['project' => $project,'users' => $users]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
        $testers = DB::table('users')->where('user_group','Test Engineer')->get();

        //TODO - add sweet alerts
        $projectUpdate = Project::where('id',$project->id)
            ->update([
                'pj_name'=> $request->input('title'),
                'status'=> $request->input('status'),
                'pj_description' => $request-> input('pj_description')

            ]);
        //if project was edited successfully
        if($projectUpdate){
            return redirect()->route('projects.index')
                ->with('success','Project updated successfully');
        }
        //redirect
        return back()->withInput();

    }

    public function search_projects(Request $request)
    {
        if (Auth::user()->user_group=='Manager') {

            $projects = Project::where('pj_name', 'like', '%' . $request->get('Query').'%')
                ->where('user_id', Auth::user()->id)
                ->get();
            //TODO:Check this loop
            foreach ($projects as $project) {
                $cnt = $project->bugs()->count();
                return json_encode(array($projects, $cnt));

            }

        }elseif(Auth::user()->user_group=='Test Engineer'){
            $projects = DB::table('project_user')
                ->join('projects','projects.id','project_user.project_id')
                ->where('pj_name','like','%'. $request->get('Query').'%')
                ->where('project_user.user_id',Auth::user()->id )
                ->get();

            return json_encode($projects);
        }elseif (Auth::user()->user_group == 'Developer'){
            $projects = DB::table('bugs')
                ->join('projects','projects.id','bugs.project_id')
                ->where('pj_name','like','%'. $request->get('Query').'%')
                ->where('bugs.assigned',Auth::user()->id)
                ->get();

            return json_encode($projects);

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //

        $findProject = Project::find( $project->id);

        if($findProject->bugs()->count()){
            return back()->with('errors',"$project->pj_name.".'project cannot be deleted, has bug records');
        }

        if($findProject ->delete()){
            return
                redirect()->route('projects.index')
                    ->with('success',"$findProject->pj_name.".' project deleted successfully');
        }
        return back()->withInput()->with('errors','Project could not be deleted');

    }

    public  function addtester(Request $request){
        //adds tester by manager to project
        //take a project, add a tester to it
        $testers = DB::table('users')->where('user_group','Test Engineer')->get();

        $project =Project::find($request->input('project_id'));

        if(Auth::user()->id == $project->user_id){

            $tester = User::where('email',$request->input('email'))->first();
            //Checks if user is already added to the project
            $projectUser = ProjectUser::where('user_id',$tester->id)
                ->where('project_id',$project->id)
                ->first();
            if($projectUser){
                //if user already exists
                return redirect()->route('projects.show',['project'=>$project->id,'testers'=> $testers])
                    ->with('errors',$request->input('email').' is already a member of this project');
            }

            if($tester && $project){
                $project->users()->attach($tester->id);// can use toggle instead of attach, to remove user if alrady in DB
                auth()->user()->notify(new AddedToProject($project,$tester));
                $tester->notify(new AddedToProject($project,$tester));

                return redirect()->route('projects.show',['project'=>$project->id,'testers'=> $testers])
                    ->with('success',$request->input('email').' was added to the project successfully');
            }

        }
        return redirect()->route('projects.show',['project'=>$project->id,'testers'=> $testers])
            ->with('errors','Error adding user to project');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.dashboard')
@section('content')

    <div class="content-wrapper">

        <div class="row">
            <div class="col-md-12">
                <div class="card" style="margin: 3rem;">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-9">
                                <h4 class="card-title">Create New Project</h4>
                            </div>
                        </div>
                    </div>
                             <!-- /.card-header -->
                        <!-- form start -->
                    <div class="row">
                        <div class="col-12">
                        <form action ="{{route('projects.store')}}" method="post">
                            {{csrf_field() }}
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-8">
                                        <div class="form-group">
                                            <label for="inputName">Project Title</label>
                                            <input type="text" class="form-control" name="pj_name" placeholder="Enter name" required>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="owner">Manager</label>
                                            <select class="form-control" name="owner" required>
                                                <option value="">...</option>

                                            @foreach($users as $user)

                                                    <option value="{{$user->name.' '.$user->lastname}}">{{$user->name.' '.$user->lastname}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-6">
                                        <div class="form-group">
                                            <label for="projectType">Select Type</label>
                                            <select class="form-control" name="pj_type">

                                                <option>Maintenance</option>
                                                <option>Conversion</option>

                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-8">
                                        <div class="form-group">
                                            <label>Project Description</label>
                                            <textarea class="form-control" rows="2" name="pj_description" placeholder="Enter ... " required></textarea>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="card-footer">
                                <input type="submit" class="btn btn-primary" value="Submit">
                            </div>


                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>
        Projects | BugTraq
    </title>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{{asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('dist/css/adminlte.min.css') }}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <a class="navbar-brand" href="#"> Projects</a>

        </ul>



        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">

            <!-- Authentication Links -->
            @guest
                <li><a href="{{ route('login') }}">Login</a></li>
                <li><a href="{{ route('register') }}">Register</a></li>
            @else
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                        <i class="far fa-user"></i>
                        {{ Auth::user()->name. ' '.Auth::user()->lastname }} <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-sm-right">
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                            <div class="media">
                                <div class="media-body">
                                    Logout
                                </div>
                            </div>
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{url('home')}}" class="brand-link">
            <img src="{{ asset('dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">BUG-TRAQ</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="../../uploads/avatars/{{Auth::user()->avatar}}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{Auth::user()->name.' '.Auth::user()->lastname}}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item">
                        <a href="{{url('/home')}}" class="nav-link active">
                            <i class="nav-icon fas fa-tachometer-alt"></i>
                            <p>
                                Home
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{url('projects')}}" class="nav-link">
                            <i class="nav-icon fas fa-calendar-alt"></i>
                            <p>
                                Projects
                            </p>
                            @if(Auth::user()->user_group =='Manager')
                                <span class="badge badge-info right">{{\App\Project::where('user_id', Auth::user()->id)->count()}}</span>

                            @endif

                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{url('bugs')}}" class="nav-link">
                            <i class="nav-icon fas fa-bug"></i>
                            <p>
                                Bugs
                            </p>
                        </a>
                    </li>
                    {{--<li class="nav-item" >--}}
                    {{--<a href="{{url('calendar')}}" class="nav-link">--}}
                    {{--<i class="nav-icon fas fa-calendar-alt"></i>--}}
                    {{--<p>--}}
                    {{--My Timesheet--}}
                    {{--</p>--}}
                    {{--</a>--}}
                    {{--</li>--}}
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-copy"></i>
                            <p>
                                Reports & Analysis
                                <i class="fas fa-angle-left right"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{url('project_reports')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Project Reports</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{url('bug_reports')}}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Bug Reports</p>
                                </a>
                            </li>

                        </ul>
                    </li>

                    <li class="nav-header">USER</li>
                    <li class="nav-item">
                        <a href="/users/{{Auth::user()->id}}" class="nav-link">
                            <i class="nav-icon fas fa-user-alt"></i>
                            <p>
                                Profile
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <div class="row">

            <div class="col-md-12">
                <div class="card" style="margin: 3rem;">
                    <div class="card-header">
                        <h1 class="title">Edit Project details</h1>
                    </div>
                    <div class="card-body">

                        <form method="post" action ="{{route('projects.update',[$project->id])}}">
                            {{csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="row">
                                <div class="col-md-5 px-3">
                                    <div class="form-group">
                                        <label for="project-name">Project Title</label>
                                        <input type="text" class="form-control" name="title"  value="{{$project->pj_name}}" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-5 px-3">
                                    <div class="form-group">
                                        <label for="owner">Project Status</label>
                                        <select class="form-control" name="status" required>
                                            <option value="">...</option>
                                            <option value="Active">Active</option>
                                            <option value="Completed">Completed</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 px-3">
                                    <div class="form-group">
                                        <label>Project Description</label>
                                        <textarea class="form-control" rows="2" name="pj_description" placeholder="Enter ... " required>{{$project->pj_description}}</textarea>
                                    </div>
                                </div>
                            </div>
                            <hr>
                            &nbsp;
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-3 px-3">
                                        <input type="submit" class="btn btn-primary btn-sm"
                                               value="Save Changes"/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div><!--Card Body-->
                </div>
            </div>

        </div>
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2019 <a href=url{{'/home'}}>BugTraq.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 1.0
        </div>
    </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="{{ asset('dist/js/demo.js') }}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{{ asset('plugins/jquery-mousewheel/jquery.mousewheel.js') }}"></script>
<script src="{{ asset('plugins/raphael/raphael.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-mapael/jquery.mapael.min.js') }}"></script>
<script src="{{ asset('plugins/jquery-mapael/maps/usa_states.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>

<!-- PAGE SCRIPTS -->
<script src="{{ asset('dist/js/pages/dashboard2.js') }}"></script>
@yield('scripts')
</body>
</html>