routes/web.php
<?php

use Carbon\Carbon;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/dash', function () {
    return view('dashboard.dashboard');
});

Route::get('/calendar',function (){
    return view('calendar');
});
Route::get('/time', function (){
    // get the current time
    $current = new Carbon('First Day of November 2020');

// add 30 days to the current time
    echo $current->toFormattedDateString();

//    $new = new Carbon('First day of November 2020');
    echo "<br>";
    echo $past =$current->subMonth()->diffForHumans();
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/projects','AdminController@showprojects')->name('admin.projects');
    Route::get('/bugs','AdminController@showbugs')->name('admin.bugs');
    Route::get('/users','AdminController@showusers')->name('admin.users');
    Route::delete('/projects/destroy/{id}','AdminController@destroyProject')->name('admin.projects.destroy');
    Route::get('/pj_details/{id}','AdminController@show_project_details');
    Route::get('/bg_details/{id}','AdminController@show_bug_details');
    Route::get('/user_details/{id}','AdminController@show_user_details');
    Route::get('/user_edit/{id}', 'AdminController@edit_user');
    Route::put('/bug_edit/{id}','AdminController@edit_bug')->name('admin.bugs.update');
    Route::delete('/users/destroy/{id}', 'AdminController@userDelete')->name('admin.users.destroy');
    Route::delete('/bugs/destroy/{id}','AdminController@bugDelete')->name('admin.bugs.destroy');
    Route::post('/user_reg','AdminController@register_user')->name('admin.users.create');
    Route::put('/projects/{id}','AdminController@editProject')->name('admin.projects.update');
});

Route::middleware(['auth'])->group(function () {
    Route::post('projects/adduser','ProjectsController@addtester')->name('projects.addtester');
    Route::get('bugs/create/{project_id?}', 'BugsController@create');
    Route::resource('projects', 'ProjectsController');
    Route::resource('bugs', 'BugsController');
    Route::resource('users', 'UsersController');
    Route::resource('events', 'EventController');
    Route::resource('comments','CommentsController');
    Route::get('bug_reports','ReportsController@bugs');
    Route::get('project_reports','ReportsController@projects');
    Route::post('bug_pdf_export','ReportsController@bug_export');
    Route::get('/bug_details/{id}','ReportsController@pdf_bug');
    Route::get('projects_pdf_export','ReportsController@project_export');
    Route::post('fileUpload',['as' => 'image.add','uses' => 'UsersController@avatarUpload']);
    Route::post('attachmentUpload',['as' =>'bug_attachment.add', 'uses'=>'BugsController@attachmentUpload']);
    Route::post('/projects/search', ['as' => 'search_projects', 'uses' => 'ProjectsController@search_projects']);
    Route::post('bugs/search', ['as' => 'search_bugs', 'uses' => 'BugsController@search_bugs']);
    Route::get('/help','HelpController@index');
    Route::get('/faq/{faq}', 'HelpController@show')->name('help.faq');

    Route::get('/markAsRead', function (){
        auth()->user()->unreadNotifications->markAsRead();
    });
});

resources/views/admin/bg_details.blade.php
@extends('layouts.master')
@section('title')
    Bugs | Admin |BugTraq
@endsection

@section('content')

    <div class="content-wrapper">

        <div class="row">
            <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
                <div class="row">
                    <div class="col-12">
                        <div class="card" style="margin-left: 3rem;margin-top: 2rem">
                            <div class="card-header">
                                <div class="row">
                                    <div class="col-md-9">
                                        <h4 class="card-title"><strong>{{$bug->title}}</strong> :Bug Information</h4>

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">

                                        <div class="form-body">


                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Assigned To:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static"> {{$bug->assigned}} </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Due On:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->due_date}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->
                                                </div>
                                                <!--/row-->
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Project:</label>
                                                            <div class="col-md-7">
                                                                @if($bug->projects)
                                                                <p class="form-control-static">{{$bug->projects->pj_name}}</p>
                                                                    @else
                                                                    <p class="form-control-static text-danger">Cannot be retrieved</p>
                                                                @endif
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            {{--TODO: Reveiw this section please based on authentication--}}
                                                            <label class="control-label text-right col-md-5">Status:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->status}}</p>

                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->

                                                </div>
                                                <!--/row-->
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Priority:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->priority}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Classification:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->type}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->
                                                </div>
                                                <!--/row-->
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Created:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->created_at}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Updated:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->updated_at}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <!--/span-->

                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Reported by:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->reporter}}</p>
                                                            </div>
                                                        </div>
                                                    </div>


                                                    <!--/span-->
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group row">
                                                            <label class="control-label text-right col-md-5">Description:</label>
                                                            <div class="col-md-7">
                                                                <p class="form-control-static">{{$bug->description}}</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                            <hr>

                                        </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                &nbsp;

            </div>
            <!--Start of Sidebar-->
            <div class="col-sm-3 col-md-3 col-lg-3 pr-4 pt-5 pull-right">
                <div class="sidebar-module sidebar-module-inset">
                    <div class="sidebar-module">

                        <h4>Actions</h4>
                        <br class="list-unstyled">
                        </br>
                            <li><a href="#" onclick="
                        var  result=confirm('You are about to delete this bug, proceed?')
                            if(result){
                                event.preventDefault();
                                document.getElementById('delete-bug').submit();
                            }


                            ">
                                    <i class="fas fa-trash"></i>Delete Bug
                                </a>
                                <form id="delete-bug" action="{{route('admin.bugs.destroy',$bug->id)}}"
                                      method="POST" style="display:none">
                                    <input type="hidden" name="_method" value="delete">
                                    {{csrf_field()}}
                                </form>
                            </li>
                            <br/>
                        </ol>

                    </div>


                </div><!--end of sidebar-->
            </div>
        </div>




    </div><!-- end of major row-->




    </div><!--end of content wrapper -->

@endsection
@section('scripts')
    <!-- <script src="../../assets/demo/demo.js"></script> -->

    <script src="../../../public/plugins/jquery/jquery.min.js"></script>
@endsection

resources/views/admin/bugs.blade.php
@extends('layouts.master')

@section('title')
    Bugs | Admin
@endsection


@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="card" style="margin: 2rem">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-9">
                                <h4 class="card-title"> List of Bugs Reported</h4></div>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table" id="bg_table">
                                    <thead class=" text-primary">
                                    <th></th>
                                    <th>
                                        Bug Title
                                    </th>
                                    <th>
                                        Priority
                                    </th>


                                    <th>
                                        Created
                                    </th>
                                    <th>
                                        Reporter
                                    </th>
                                    <th>
                                        Dev Assigned
                                    </th>
                                    <th>
                                        Due Date
                                    </th>

                                    <th class="text-right">
                                        Status
                                    </th>
                                    <th width="180px">

                                    </th>
                                    </thead>
                                    <tbody>
                                    @foreach($bugs as $indexKey => $bug)
                                        <tr>
                                            <td><b>{{$indexKey+1}}.</b></td>
                                            <td>{{$bug->title}}</td>
                                            <td>{{$bug->priority}}</td>

                                            <td>{{$bug->created_at}}</td>
                                            <td>{{$bug->reporter}}</td>
                                            <td>{{$bug->name.' '.$bug->lastname}}</td>
                                            <td>{{$bug->due_date}}</td>
                                            <td class="text-fuchsia text-right">{{$bug->status}}</td>
                                            <td>
                                                <a class="btn btn-sm btn-success" href="{{url('admin/bg_details/'.$bug->id)}}">Details</a>

                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready( function () {
            $('#bg_table').DataTable({
                "lengthMenu":[[5,10,15,20,-1],[5,10,15,20,"All"]],
                "searching":      true,
                "ordering":       true,
            });
        });
    </script>
@endsection

resources/views/admin/user_details.blade.php
@extends('layouts.master')
@section('title')
    EditUser| Admin | BugTraq
@endsection

@section('content')

    <div class="content-wrapper">
        <div class="row">

            <div class="col-md-12">
                <div class="card" style="margin: 3rem;">
                    <div class="card-header">
                        <h3 class="title">Delete {{ $user->name }}'s Profile</h3>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{route('admin.users.destroy', $user->id)}}" >
                        {{--<form method="post" action ="{{route('users.update',[$user()->id])}}">--}}
                            {{csrf_field() }}
                            <input type="hidden" name="_method" value="delete">
                            <div class="row">
                                <div class="col-md-5 px-3">
                                    <div class="form-group">
                                        <label for="email">First Name</label>
                                        <input type="text" class="form-control" name="fname" placeholder="Email" value="{{$user->name}}" readonly>
                                    </div>
                                </div>
                                <div class="col-md-5 px-3">
                                    <div class="form-group">
                                        <label for="email">Last Name</label>
                                        <input type="text" class="form-control" name="lname" placeholder="Email" value="{{$user->lastname}}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-5 px-3">
                                    <div class="form-group">
                                        <label for="email">Email address</label>
                                        <input type="text" class="form-control" name="email" placeholder="Email" value="{{$user->email}}">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-5 px-3">
                                    <div class="form-group">
                                        <label for="phone">Phone No.</label>
                                        <input type="tel" class="form-control" name="phone" placeholder="Contact Phone" value="{{$user->phone_no}}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <div class="col-md-3 px-3">
                                        <input type="submit" class="btn btn-danger btn-sm"
                                               value="Delete User"/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div><!--Card Body-->
                </div>
            </div>

        </div>
    </div>



@endsection
    @section('scripts')
        <!-- <script src="../../assets/demo/demo.js"></script> -->

            <script src="../../../public/plugins/jquery/jquery.min.js"></script>
@endsection