routes/web.php
<?php

use Carbon\Carbon;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/dash', function () {
    return view('dashboard.dashboard');
});

Route::get('/calendar',function (){
    return view('calendar');
});
Route::get('/time', function (){
    // get the current time
    $current = new Carbon('First Day of November 2020');

// add 30 days to the current time
    echo $current->toFormattedDateString();

//    $new = new Carbon('First day of November 2020');
    echo "<br>";
    echo $past =$current->subMonth()->diffForHumans();
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/projects','AdminController@showprojects')->name('admin.projects');
    Route::get('/bugs','AdminController@showbugs')->name('admin.bugs');
    Route::get('/users','AdminController@showusers')->name('admin.users');
    Route::delete('/projects/destroy/{id}','AdminController@destroyProject')->name('admin.projects.destroy');
    Route::get('/pj_details/{id}','AdminController@show_project_details');
    Route::get('/bg_details/{id}','AdminController@show_bug_details');
    Route::get('/user_details/{id}','AdminController@show_user_details');
    Route::get('/user_edit/{id}', 'AdminController@edit_user');
    Route::put('/bug_edit/{id}','AdminController@edit_bug')->name('admin.bugs.update');
    Route::delete('/users/destroy/{id}', 'AdminController@userDelete')->name('admin.users.destroy');
    Route::delete('/bugs/destroy/{id}','AdminController@bugDelete')->name('admin.bugs.destroy');
    Route::post('/user_reg','AdminController@register_user')->name('admin.users.create');
    Route::put('/projects/{id}','AdminController@editProject')->name('admin.projects.update');
});

Route::middleware(['auth'])->group(function () {
    Route::post('projects/adduser','ProjectsController@addtester')->name('projects.addtester');
    Route::get('bugs/create/{project_id?}', 'BugsController@create');
    Route::resource('projects', 'ProjectsController');
    Route::resource('bugs', 'BugsController');
    Route::resource('users', 'UsersController');
    Route::resource('events', 'EventController');
    Route::resource('comments','CommentsController');
    Route::get('bug_reports','ReportsController@bugs');
    Route::get('project_reports','ReportsController@projects');
    Route::post('bug_pdf_export','ReportsController@bug_export');
    Route::get('/bug_details/{id}','ReportsController@pdf_bug');
    Route::get('projects_pdf_export','ReportsController@project_export');
    Route::post('fileUpload',['as' => 'image.add','uses' => 'UsersController@avatarUpload']);
    Route::post('attachmentUpload',['as' =>'bug_attachment.add', 'uses'=>'BugsController@attachmentUpload']);
    Route::post('/projects/search', ['as' => 'search_projects', 'uses' => 'ProjectsController@search_projects']);
    Route::post('bugs/search', ['as' => 'search_bugs', 'uses' => 'BugsController@search_bugs']);
    Route::get('/help','HelpController@index');
    Route::get('/faq/{faq}', 'HelpController@show')->name('help.faq');

    Route::get('/markAsRead', function (){
        auth()->user()->unreadNotifications->markAsRead();
    });
});

app/Bug.php
<?php

namespace App;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Bug extends Model
{
    //
    protected $fillable=[
        'title',
        'description',
        'reporter',
        'reporter_id',
        'project_id',
        'assigned',
        'type',
        'due_date',
        'priority',
        'status',
    ];

    protected $dates = ['due_date'];


    public function projects(){
        return $this->hasOne('App\Project','id','project_id');
    }
    public function users(){
        return $this->hasOne('App\User');
    }
    public function priority(){
        return $this->hasOne('App\Priority');
    }
    public function status(){
        return $this->hasOne('App\BugStatus');
    }
    public function comments(){
        return $this->morphMany('App\Comment','commentable');
    }
    public function bug_attachments(){
        return $this->hasMany('App\BugAttachment');
    }
    public function getDueDateAttribute($value){
        return Carbon::parse($value)->diffForHumans();
    }
}

app/Http/Controllers/BugsController.php
<?php

namespace App\Http\Controllers;

use App\Bug;
use App\BugAttachment;
use App\Project;
use App\ProjectUser;
use App\User;
use App\Notifications\AddedToProject;

use App\Charts\BugChart;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class BugsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $bug = Bug::orderBy('project_id')
        // ->pluck('project_id','status');

        $bug = DB::table('bugs')
            ->select('status', DB::raw('count(*) as total'))
            ->groupBy('status')
            ->pluck('total','status');
        //return $bug->keys();

        //return $bug->values();


        if (Auth::user()->user_group=='Developer'){
            $bugs = DB::table('users')
                ->join('bugs','bugs.assigned','users.id')
                ->where('bugs.assigned',Auth::user()->id)
                ->get();


        }
        elseif (Auth::user()->user_group=='Test Engineer'){
//            $bugs = Bug::where('reporter', Auth::user()->name .' '.Auth::user()->lastname)->get();

            $bugs = DB::table('users')
                ->join('bugs','bugs.assigned','users.id')
                ->where('reporter_id', Auth::user()->id)
                ->get();
        }
        else{
            $bugs =DB::table('users')
                ->join('bugs','bugs.assigned','users.id')
                ->get();
        }

        return view('bugs.index', compact('bugs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($project_id =null)//null is the default value assigned if id not entered
    {
        //
        $devs = User::where('user_group','Developer')->get();

        $projects = null;

        if(!$project_id){
            $projects = Project::where('user_id',Auth::user()->id)->get();
        }else{
            $projects = Project::where('id',$project_id)->first();
        }
        return view('bugs.create',['project_id'=>$project_id,'projects'=>$projects,'devs'=> $devs]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'due_date' => 'date|after:today'
        ]);
        if(Auth::check()) {
            $bug = Bug::create([
                'project_id'=>$request->input('project_id'),
                'title'=>$request->input('title'),
                'reporter'=>Auth::user()->name.' '.Auth::user()->lastname,
                'reporter_id'=>Auth::user()->id,
                'type'=>$request->input('bug_type'),
                'description' =>$request->input('description'),
                'priority'=>$request->input('priority'),
                'assigned' => $request->input('assigned'),
                'due_date'=>$request->input('due_date')
            ]);
            //dd($bug);
            $project =Project::find($request->input('project_id'));



            if ($bug && $project) { //if bug was created successfully

                $projectUser = ProjectUser::where('user_id',$request->input('assigned'))
                                            ->where('project_id',$request->input('project_id'))
                                            ->first();
                $dev = User::where('id',$request->input('assigned'))->first();
                if (!$projectUser){
                    $project->users()->attach($request->input('assigned'));

                    $dev->notify(new AddedToProject($project,$dev));
                    auth()->user()->notify(new AddedToProject($project,$dev));
                }


                return redirect()->to('/projects/'.$request->input('project_id'))
                    //return redirect()->route('bugs.show', ['bug' => $bug->id])
                    ->with('success', 'Bug created successfully');
            }else{
                return back()->withInput()->with('errors','Error creating new bug');

            }

        }
        //if not created successfully
        return back()->withInput()->with('errors','Error creating new bug');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bug  $bug
     * @return \Illuminate\Http\Response
     */
    public function show(Bug $bug)
    {
        //
        $bug = Bug::where('id',$bug->id)->first();
        $bugs = DB::table('bugs')
            ->join('users','users.id','bugs.assigned')
            ->where('bugs.id',$bug->id)
            ->first();
        $devs = User::where('user_group','Developer')->get();

        $comments = $bug->comments;


        return view('bugs.show',['bugs'=>$bugs,'bug'=>$bug,'comments'=>$comments,'devs'=>$devs]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bug  $bug
     * @return \Illuminate\Http\Response
     */
    public function edit(Bug $bug)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bug  $bug
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bug $bug)
    {
        //
        $this->validate($request,[
            'due_date' => 'date|after:today'
        ]);
        $bugUpdate = Bug::where('id',$bug->id)
            ->update([
                'type'=>$request->input('bug_type'),
                'description'=>$request->input('description'),
                'priority'=>$request->input('priority'),
                'assigned'=>$request->input('dev'),
                'due_date'=>$request->input('due_date'),
                'status'=>$request->input('status')
            ]);
        if($bugUpdate){
            return redirect()->to('/bugs/'.$bug->id)
                ->with('success','Bug Status changed successfully');


        }
    }


    public function search_bugs(Request $request)
    {
        if(Auth::user()->user_group == 'Developer'){
            $bugs = DB::table('users')
                ->join('bugs','bugs.assigned','users.id')
                ->where('title','like','%' . $request->get('Query').'%')
                ->where('assigned',Auth::user()->id)
                ->get();

//            $bugs = Bug::where('title','like','%' . $request->get('Query').'%')
//                ->where('assigned',Auth::user()->name. ' '.Auth::user()->lastname)
//                ->get();
        }

        elseif (Auth::user()->user_group == 'Test Engineer'){

            $bugs = DB::table('users')
                ->join('bugs','bugs.assigned','users.id')
                ->where('title','like','%' . $request->get('Query').'%')
                ->where('reporter_id',Auth::user()->id)
                ->get();
//            $bugs = Bug::where('title', 'like','%'. $request->get('Query').'%')
//                ->where('reporter', Auth::user()->name .' '.Auth::user()->lastname)
//                ->get();

        }

        else {
            $bugs = DB::table('users')
                ->join('bugs','bugs.assigned','users.id')
                ->where('title','like','%'.$request->get('Query').'%')
                ->get();
//            $bugs = Bug::
//                ->get();


        }

        return json_encode($bugs);
    }

    public function attachmentUpload(Request $request){
        $this->validate($request,[
            'image' => 'image|mimes:jpeg,png,jpg|max:2048'
        ]);
        $devs = User::where('user_group','Developer')->get();
        $bug = Bug::find($request->input('bug_id'));
        $comments = $bug->comments;

        if ($request->hasFile('attachments')){

            foreach ($request->attachments as $file){
                $filename = $file->getClientOriginalName();
                //print_r($filename);

                $destinationPath = public_path('uploads/attachments');
                $file->move($destinationPath, $filename);

                $attAdded = BugAttachment::create([
                    'att_name'=>$filename,
                    'bug_id'=>$request->input('bug_id')
                ]);


            }
            if ($attAdded){
                // return view('bugs.show',compact('devs','bug','comments'));

                return redirect()->to('/bugs/'.$bug->id)
                    ->with('success','Attachments added successfully');
            }
        }
        return back()->with('errors','Error adding attachments');

    }


    public function destroy(Bug $bug)
    {
        //
        $findBug = Bug::find($bug->id);
        $comments = $findBug->comments();

        if($findBug ->delete()){
            $comments->delete();
            return redirect()->route('bugs.index')
                ->with('success',"$findBug->title".' (bug) deleted successfully');
        }
        return back()->withInput()->with('errors','Bug could not be deleted');
    }
}

resources/views/bugs/create.blade.php
@extends('layouts.dashboard')
@section('title','Create | Bug')

@section('content')

    <div class="content-wrapper">

        <div class="row">
            <div class="col-md-12">
                <div class="card" style="margin: 3rem;">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-9">
                                <h4 class="card-title">Report New Bug for <strong><span class="highlight primary">{{$projects->pj_name}}</span></strong></h4>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <div class="row">
                        <div class="col-md-12">
                            <form action ="{{route('bugs.store')}}" method="post">
                                {{csrf_field() }}
                                <div class="card-body">
                                    @if($projects != null)
                                        <input type="hidden" name="project_id"
                                               class="form-control"
                                               value="{{$project_id}}"/>
                                    @endif
                             <div class="row">
                                        <div class="col-8">
                                            <div class="form-group">
                                                <label for="Title">Bug Title</label>
                                                <input type="text" class="form-control" name="title" placeholder="Enter Title" required>
                                            </div>
                                 </div>
                             </div>


                           <div class="row">
                               <div class="col-5">
                                   <div class="form-group">
                                       <label for="bugType">Select TYPE</label>
                                       <select class="form-control" name="bug_type">

                                           <option>Functional</option>
                                           <option>Communication
                                           <option>Missing Commands</option>
                                           <option>Syntactic</option>
                                           <option>Error handling</option>
                                           <option>Calculation</option>
                                           <option>Control flow</option>
                                       </select>
                                   </div>
                               </div>
                               <div class="col-1">
                               </div>
                               <div class="col-5">
                                   <div class="form-group">
                                       <label for="Assigned">Assign To:(Dev)</label>
                                       <select class="form-control" name="assigned" data-placeholder="...">
                                           <option value="">...</option>
                                           @foreach($devs as $dev)
                                               <option value="{{$dev->id}}">{{$dev->name.' '.$dev->lastname}}</option>
                                           @endforeach
                                       </select>
                                   </div>
                               </div>
                           </div>
                            <div class="row">
                                <div class="col-5">
                                <div class="form-group">
                                        <label for="bugType">Select Priority</label>
                                        <select class="form-control" name="priority">
                                            <option>Major</option>
                                            <option>Medium</option>
                                            <option>Minor</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-1"></div>
                                <div class="col-5">
                                    <div class="form-group">
                                        <label>Due Date:</label>

                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                              <span class="input-group-text">
                                                <i class="far fa-calendar-alt"></i>
                                              </span>
                                            </div>

                                            <input type="date" name="due_date" class="form-control float-right" id="reservation" data-inputmask-alias="datetime" data-inputmask-inputformat="dd/mm/yyyy" data-mask>
                                        </div>
                                        <!-- /.input group -->
                                    </div>
                                </div>
                                </div>
                                        <!--TODO : add attachment section -->
                                <div class="row">
                                    <div class="col-8">
                                        <div class="form-group">
                                            <label>Bug Description</label>
                                            <textarea class="form-control" rows="2" name="description" placeholder="Enter ... " required></textarea>
                                        </div>
                                    </div>
                                </div>
                                </div>


                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <input type="submit" class="btn btn-primary" value="Submit">
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bugs/index.blade.php
@extends('layouts.dashboard')

@section('title','Bugs')


@section('content')
    <div class="content-wrapper">

        <div class="row">
            <div class="col-md-12">

                <div class="card" style="margin: 2rem;">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-9">
                                @if(Auth::user()->user_group=='Manager')
                                    <h4 class="card-title">All Bugs Reported</h4></div>

                            @elseif(Auth::user()->user_group=='Test Engineer')
                                <h4 class="card-title">Bugs Reported</h4></div>

                        @elseif(Auth::user()->user_group=='Developer')
                            <h4 class="card-title">Bugs Assigned</h4></div>
                    @endif

                    <div class="col-md-3">
                        <form class="form-inline ml-3">
                            <div class="input-group input-group-sm">
                                @if(Auth::user()->user_group=='Manager')
                                    <input class="form-control form-control-navbar" type="search" id="search_bug_mgr" placeholder="Search" aria-label="Search">

                                @elseif(Auth::user()->user_group=='Test Engineer')
                                    <input class="form-control form-control-navbar" type="search" id="search_bug_tst" placeholder="Search" aria-label="Search">

                                @elseif(Auth::user()->user_group=='Developer')
                                    <input class="form-control form-control-navbar" type="search" id="search_bug_dev" placeholder="Search" aria-label="Search">

                                @endif

                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead class=" text-primary">


                            <th>
                                Bug Title
                            </th>
                            <th>
                                Priority
                            </th>
                            <th>
                                Created
                            </th>
                            @if(Auth::user()->user_group!=='Test Engineer')

                            <th>
                                Reporter
                            </th>
                            @endif

                          @if(Auth::user()->user_group!=='Developer')
                            <th>
                                Dev Assigned
                           @endif

                            <th>
                                Due Date
                            </th>

                            <th class="text-right">
                                Status
                            </th>
                            <th>
                                Action
                            </th>
                            </thead>

                            <tbody id="dynamic_data">
                            @if(count($bugs) < 1)
                                <tr>
                                    <td>No bugs found</td>
                                </tr>
                            @else
                                @foreach($bugs as $indexkey => $bug)
                                    <tr>
                                        {{--<td>{{$indexkey+1}}<b>.</b></td>--}}
                                        <td>{{$bug->title}}</td>
                                        <td>{{$bug->priority}}</td>
                                        <td>{{$bug->created_at}}</td>
                                        @if(Auth::user()->user_group!=='Test Engineer')

                                             <td>{{$bug->reporter}}</td>
                                        @endif
                                        @if(Auth::user()->user_group!=='Developer')

                                         <td>{{$bug->name.' '.$bug->lastname}}</td>
                                        @endif
                                        <td>{{$bug->due_date}}</td>
                                        <td>{{$bug->status}}</td>
                                        <td>
                                            <a class="btn btn-sm btn-success" href="{{route('bugs.show',$bug->id)}}">Show</a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>


    <script>
        //For managers
        $('body').on('keyup','#search_bug_mgr', function () {
            var Query = $(this).val();
            //console.log(Query)

            $.ajax({
                method: "POST",
                url : '{{route('search_bugs')}}',
                dataType: 'json',
                data : {
                    '_token' : '{{ csrf_token() }}',
                    Query: Query
                },
                success : function (res) {
                    //console.log(res)
                    var tableRow = '';

                    $('#dynamic_data').html('');

                    $.each(res, function (index, value) {
                        var bugUrl = '/bugs/'+value.id;
                        tableRow =  '<tr>' +
                            // '<td>'+ value.id +'</td>' +
                            '<td>'+ value.title+'</td>' +
                            '<td>'+ value.priority +'</td>' +
                            '<td>'+ value.created_at+'</td>' +
                            '<td>'+ value.reporter+'</td>' +
                            '<td>'+ value.name+' '+value.lastname+'</td>' +
                            '<td>'+ value.due_date+'</td>' +
                            '<td>'+ value.status+'</td>' +
                            '<td><a class="btn btn-sm btn-success" href="'+bugUrl+'" style="color:white">Show</a> </td>' +


                            '</tr>';

                        $('#dynamic_data').append(tableRow);
                    });
                }
            });
        }) ;

        //For test engineers
        $('body').on('keyup','#search_bug_tst', function () {
            var Query = $(this).val();
            //console.log(Query)

            $.ajax({
                method: "POST",
                url : '{{route('search_bugs')}}',
                dataType: 'json',
                data : {
                    '_token' : '{{ csrf_token() }}',
                    Query: Query
                },
                success : function (res) {
                    //console.log(res)
                    var tableRow = '';

                    $('#dynamic_data').html('');

                    $.each(res, function (index, value) {
                        var bugUrl = '/bugs/'+value.id;
                        let a =1;
                        tableRow =  '<tr>' +
                            '<td>'+ value.title+'</td>' +
                            '<td>'+ value.priority +'</td>' +
                            '<td>'+ value.created_at+'</td>' +
                            '<td>'+ value.name+' '+value.lastname+'</td>' +
                            '<td>'+ value.due_date+'</td>' +
                            '<td>'+ value.status+'</td>' +
                            '<td><a class="btn btn-sm btn-success" href="'+bugUrl+'" style="color:white">Show</a> </td>' +


                            '</tr>';

                        $('#dynamic_data').append(tableRow);
                        a++;

                    });
                }
            });
        }) ;


        //For developers
        $('body').on('keyup','#search_bug_dev', function () {
            var Query = $(this).val();
            //console.log(Query)

            $.ajax({
                method: "POST",
                url : '{{route('search_bugs')}}',
                dataType: 'json',
                data : {
                    '_token' : '{{ csrf_token() }}',
                    Query: Query
                },
                success : function (res) {
                    //console.log(res)
                    var tableRow = '';

                    $('#dynamic_data').html('');

                    $.each(res, function (index, value) {
                        var bugUrl = '/bugs/'+value.id;
                        tableRow =  '<tr>' +
                            '<td>'+ value.title+'</td>' +
                            '<td>'+ value.priority +'</td>' +
                            '<td>'+ value.created_at+'</td>' +
                            '<td>'+ value.name+' '+value.lastname+'</td>' +

                            '<td>'+ value.due_date+'</td>' +
                            '<td>'+ value.status+'</td>' +
                            '<td><a class="btn btn-sm btn-success" href="'+bugUrl+'" style="color:white">Show</a> </td>' +


                            '</tr>';

                        $('#dynamic_data').append(tableRow);
                    });
                }
            });
        }) ;

    </script>
@endsection